// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: i13eimJzTqVDJ7txL3iZyA
// Component: N3vyyAXknm
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import HomeWorkButton from "../../HomeWorkButton"; // plasmic-import: L6I88p1sTt/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: i13eimJzTqVDJ7txL3iZyA/projectcss
import * as sty from "./PlasmicHomePage.module.css"; // plasmic-import: N3vyyAXknm/css

import SettingIcon from "./icons/PlasmicIcon__Setting"; // plasmic-import: ZVQoLok7Mn/icon
import NotificationIcon from "./icons/PlasmicIcon__Notification"; // plasmic-import: n7cyuplJUX/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: SosGjje1vC/icon
import ArrowRightCircleIcon from "./icons/PlasmicIcon__ArrowRightCircle"; // plasmic-import: ZkOzDLRbb4c/icon
import ArrowLeftCircleIcon from "./icons/PlasmicIcon__ArrowLeftCircle"; // plasmic-import: f8fRLo_gvW/icon
import ArrowRightCircle2Icon from "./icons/PlasmicIcon__ArrowRightCircle2"; // plasmic-import: vr0xJoldp1S/icon
import Ellipse2Icon from "./icons/PlasmicIcon__Ellipse2"; // plasmic-import: AuqRINwL7Zy/icon
import ArrowRightCircle3Icon from "./icons/PlasmicIcon__ArrowRightCircle3"; // plasmic-import: 1LCBJpbHDZy/icon

export type PlasmicHomePage__VariantMembers = {};

export type PlasmicHomePage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomePage__VariantsArgs;
export const PlasmicHomePage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomePage__ArgsType = {};
type ArgPropType = keyof PlasmicHomePage__ArgsType;
export const PlasmicHomePage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomePage__OverridesType = {
  root?: p.Flex<"div">;
  patientHomeScreen?: p.Flex<"div">;
  appBar?: p.Flex<"div">;
  settings?: p.Flex<"div">;
  headLine?: p.Flex<"div">;
  h1Headline?: p.Flex<"div">;
  notification?: p.Flex<"div">;
  searchBar?: p.Flex<"div">;
  frame206?: p.Flex<"div">;
  seachButton?: p.Flex<"div">;
  rectangle8?: p.Flex<"div">;
  group89?: p.Flex<"div">;
  tabs?: p.Flex<"div">;
  tabNames?: p.Flex<"div">;
  headLine2?: p.Flex<"div">;
  h1Headline2?: p.Flex<"div">;
  headLine3?: p.Flex<"div">;
  h1Headline3?: p.Flex<"div">;
  tab?: p.Flex<"div">;
  activeTabLine?: p.Flex<"div">;
  frame217?: p.Flex<"div">;
  rectangle389?: p.Flex<"div">;
  tabContent?: p.Flex<"div">;
  patientSessions?: p.Flex<"div">;
  sessionWidget?: p.Flex<"div">;
  arrowLeftCircle?: p.Flex<"div">;
  frame89?: p.Flex<"div">;
  frame90?: p.Flex<"div">;
  headLine4?: p.Flex<"div">;
  h1Headline4?: p.Flex<"div">;
  body?: p.Flex<"div">;
  body10Pt?: p.Flex<"div">;
  arrowRightCircle?: p.Flex<"div">;
  singleScrollable?: p.Flex<"div">;
  patientActivityComponent?: p.Flex<"div">;
  patientActivityComponent2?: p.Flex<"div">;
  frame91?: p.Flex<"div">;
  frame92?: p.Flex<"div">;
  headLine5?: p.Flex<"div">;
  h1Headline5?: p.Flex<"div">;
  progressBarNot?: p.Flex<"div">;
  frame1?: p.Flex<"div">;
  frame228?: p.Flex<"div">;
  frame246?: p.Flex<"div">;
  body10Pt7?: p.Flex<"div">;
  patientActivityComponent3?: p.Flex<"div">;
  patientActivityComponent4?: p.Flex<"div">;
  frame93?: p.Flex<"div">;
  frame94?: p.Flex<"div">;
  headLine6?: p.Flex<"div">;
  h1Headline6?: p.Flex<"div">;
  progressBarNot2?: p.Flex<"div">;
  frame2?: p.Flex<"div">;
  frame229?: p.Flex<"div">;
  frame247?: p.Flex<"div">;
  body10Pt13?: p.Flex<"div">;
  patientActivityComponent5?: p.Flex<"div">;
  patientActivityComponent6?: p.Flex<"div">;
  frame95?: p.Flex<"div">;
  frame96?: p.Flex<"div">;
  headLine7?: p.Flex<"div">;
  h1Headline7?: p.Flex<"div">;
  body12?: p.Flex<"div">;
  body10Pt14?: p.Flex<"div">;
  progressBarNot3?: p.Flex<"div">;
  frame3?: p.Flex<"div">;
  frame230?: p.Flex<"div">;
  homeWork9?: p.Flex<"div">;
  body13?: p.Flex<"div">;
  body10Pt15?: p.Flex<"div">;
  percentBall9?: p.Flex<"div">;
  group98?: p.Flex<"div">;
  arrowRightCircle16?: p.Flex<"div">;
  arrowRightCircle17?: p.Flex<"div">;
  homeWork10?: p.Flex<"div">;
  body14?: p.Flex<"div">;
  body10Pt16?: p.Flex<"div">;
  percentBall10?: p.Flex<"div">;
  group99?: p.Flex<"div">;
  arrowRightCircle18?: p.Flex<"div">;
  arrowRightCircle19?: p.Flex<"div">;
  homeWork11?: p.Flex<"div">;
  body15?: p.Flex<"div">;
  body10Pt17?: p.Flex<"div">;
  percentBall11?: p.Flex<"div">;
  group100?: p.Flex<"div">;
  arrowRightCircle20?: p.Flex<"div">;
  arrowRightCircle21?: p.Flex<"div">;
  homeWork12?: p.Flex<"div">;
  body16?: p.Flex<"div">;
  body10Pt18?: p.Flex<"div">;
  percentBall12?: p.Flex<"div">;
  group101?: p.Flex<"div">;
  arrowRightCircle22?: p.Flex<"div">;
  arrowRightCircle23?: p.Flex<"div">;
  frame248?: p.Flex<"div">;
  body10Pt19?: p.Flex<"div">;
};

export interface DefaultHomePageProps {
  className?: string;
}

function PlasmicHomePage__RenderFunc(props: {
  variants: PlasmicHomePage__VariantsArgs;
  args: PlasmicHomePage__ArgsType;
  overrides: PlasmicHomePage__OverridesType;
  dataFetches?: PlasmicHomePage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"patientHomeScreen"}
            data-plasmic-override={overrides.patientHomeScreen}
            className={classNames(defaultcss.all, sty.patientHomeScreen)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"appBar"}
              data-plasmic-override={overrides.appBar}
              hasGap={true}
              className={classNames(defaultcss.all, sty.appBar)}
            >
              <div
                data-plasmic-name={"settings"}
                data-plasmic-override={overrides.settings}
                className={classNames(defaultcss.all, sty.settings)}
              >
                <SettingIcon
                  className={classNames(defaultcss.all, sty.svg__mAypw)}
                  role={"img"}
                />
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"headLine"}
                data-plasmic-override={overrides.headLine}
                hasGap={true}
                className={classNames(defaultcss.all, sty.headLine)}
              >
                <div
                  data-plasmic-name={"h1Headline"}
                  data-plasmic-override={overrides.h1Headline}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.h1Headline
                  )}
                >
                  {"Teru"}
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"notification"}
                data-plasmic-override={overrides.notification}
                className={classNames(defaultcss.all, sty.notification)}
              >
                <NotificationIcon
                  className={classNames(defaultcss.all, sty.svg__vjMiu)}
                  role={"img"}
                />
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"searchBar"}
              data-plasmic-override={overrides.searchBar}
              hasGap={true}
              className={classNames(defaultcss.all, sty.searchBar)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"frame206"}
                data-plasmic-override={overrides.frame206}
                hasGap={true}
                className={classNames(defaultcss.all, sty.frame206)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__p3DbO
                  )}
                >
                  {"Search"}
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"seachButton"}
                data-plasmic-override={overrides.seachButton}
                className={classNames(defaultcss.all, sty.seachButton)}
              >
                <div
                  data-plasmic-name={"rectangle8"}
                  data-plasmic-override={overrides.rectangle8}
                  className={classNames(defaultcss.all, sty.rectangle8)}
                />

                <VectorIcon
                  className={classNames(defaultcss.all, sty.svg__yGJvm)}
                  role={"img"}
                />
              </div>
            </p.Stack>

            <div
              data-plasmic-name={"group89"}
              data-plasmic-override={overrides.group89}
              className={classNames(defaultcss.all, sty.group89)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"tabs"}
                data-plasmic-override={overrides.tabs}
                hasGap={true}
                className={classNames(defaultcss.all, sty.tabs)}
              >
                <div
                  data-plasmic-name={"tabNames"}
                  data-plasmic-override={overrides.tabNames}
                  className={classNames(defaultcss.all, sty.tabNames)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"headLine2"}
                    data-plasmic-override={overrides.headLine2}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.headLine2)}
                  >
                    <div
                      data-plasmic-name={"h1Headline2"}
                      data-plasmic-override={overrides.h1Headline2}
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.h1Headline2
                      )}
                    >
                      {"Michelli Simpson"}
                    </div>
                  </p.Stack>

                  {false ? (
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"headLine3"}
                      data-plasmic-override={overrides.headLine3}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.headLine3)}
                    >
                      <div
                        data-plasmic-name={"h1Headline3"}
                        data-plasmic-override={overrides.h1Headline3}
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.h1Headline3
                        )}
                      >
                        {"Ariadne Nunes"}
                      </div>
                    </p.Stack>
                  ) : null}
                </div>

                <div
                  data-plasmic-name={"tab"}
                  data-plasmic-override={overrides.tab}
                  className={classNames(defaultcss.all, sty.tab)}
                >
                  <div
                    data-plasmic-name={"activeTabLine"}
                    data-plasmic-override={overrides.activeTabLine}
                    className={classNames(defaultcss.all, sty.activeTabLine)}
                  >
                    <div
                      data-plasmic-name={"frame217"}
                      data-plasmic-override={overrides.frame217}
                      className={classNames(defaultcss.all, sty.frame217)}
                    >
                      <div
                        data-plasmic-name={"rectangle389"}
                        data-plasmic-override={overrides.rectangle389}
                        className={classNames(defaultcss.all, sty.rectangle389)}
                      />
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"tabContent"}
                    data-plasmic-override={overrides.tabContent}
                    className={classNames(defaultcss.all, sty.tabContent)}
                  />
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"patientSessions"}
                data-plasmic-override={overrides.patientSessions}
                hasGap={true}
                className={classNames(defaultcss.all, sty.patientSessions)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"sessionWidget"}
                  data-plasmic-override={overrides.sessionWidget}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.sessionWidget)}
                >
                  <div
                    data-plasmic-name={"arrowLeftCircle"}
                    data-plasmic-override={overrides.arrowLeftCircle}
                    className={classNames(defaultcss.all, sty.arrowLeftCircle)}
                  >
                    <ArrowRightCircleIcon
                      className={classNames(defaultcss.all, sty.svg__lH5B)}
                      role={"img"}
                    />

                    <ArrowLeftCircleIcon
                      className={classNames(defaultcss.all, sty.svg__gWob)}
                      role={"img"}
                    />
                  </div>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame89"}
                    data-plasmic-override={overrides.frame89}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.frame89)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame90"}
                      data-plasmic-override={overrides.frame90}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.frame90)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"headLine4"}
                        data-plasmic-override={overrides.headLine4}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.headLine4)}
                      >
                        <div
                          data-plasmic-name={"h1Headline4"}
                          data-plasmic-override={overrides.h1Headline4}
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.h1Headline4
                          )}
                        >
                          {"session 3"}
                        </div>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"body"}
                        data-plasmic-override={overrides.body}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.body)}
                      >
                        <div
                          data-plasmic-name={"body10Pt"}
                          data-plasmic-override={overrides.body10Pt}
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.body10Pt
                          )}
                        >
                          {"from 12/15"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>

                  <div
                    data-plasmic-name={"arrowRightCircle"}
                    data-plasmic-override={overrides.arrowRightCircle}
                    className={classNames(defaultcss.all, sty.arrowRightCircle)}
                  >
                    {false ? (
                      <ArrowRightCircle2Icon
                        className={classNames(defaultcss.all, sty.svg__vIo0I)}
                        role={"img"}
                      />
                    ) : null}
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"singleScrollable"}
                  data-plasmic-override={overrides.singleScrollable}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.singleScrollable)}
                >
                  <div
                    data-plasmic-name={"patientActivityComponent"}
                    data-plasmic-override={overrides.patientActivityComponent}
                    className={classNames(
                      defaultcss.all,
                      sty.patientActivityComponent
                    )}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"patientActivityComponent2"}
                      data-plasmic-override={
                        overrides.patientActivityComponent2
                      }
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        sty.patientActivityComponent2
                      )}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame91"}
                        data-plasmic-override={overrides.frame91}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.frame91)}
                      >
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame92"}
                          data-plasmic-override={overrides.frame92}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.frame92)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"headLine5"}
                            data-plasmic-override={overrides.headLine5}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.headLine5
                            )}
                          >
                            <div
                              data-plasmic-name={"h1Headline5"}
                              data-plasmic-override={overrides.h1Headline5}
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.h1Headline5
                              )}
                            >
                              {"${ActivityName}"}
                            </div>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"progressBarNot"}
                            data-plasmic-override={overrides.progressBarNot}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.progressBarNot
                            )}
                          >
                            <div
                              data-plasmic-name={"frame1"}
                              data-plasmic-override={overrides.frame1}
                              className={classNames(defaultcss.all, sty.frame1)}
                            >
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.text__oSxoF
                                )}
                              >
                                {"0%"}
                              </div>
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame228"}
                        data-plasmic-override={overrides.frame228}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.frame228)}
                      >
                        <HomeWorkButton
                          _100={"_100" as const}
                          _25={"_25" as const}
                          _50={"_50" as const}
                          _75={"_75" as const}
                          className={classNames(
                            "__wab_instance",
                            sty.homeWorkButton__jtRn3
                          )}
                        />
                      </p.Stack>

                      <div
                        data-plasmic-name={"frame246"}
                        data-plasmic-override={overrides.frame246}
                        className={classNames(defaultcss.all, sty.frame246)}
                      >
                        <div
                          data-plasmic-name={"body10Pt7"}
                          data-plasmic-override={overrides.body10Pt7}
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.body10Pt7
                          )}
                        >
                          {"see all >"}
                        </div>
                      </div>
                    </p.Stack>
                  </div>

                  <div
                    data-plasmic-name={"patientActivityComponent3"}
                    data-plasmic-override={overrides.patientActivityComponent3}
                    className={classNames(
                      defaultcss.all,
                      sty.patientActivityComponent3
                    )}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"patientActivityComponent4"}
                      data-plasmic-override={
                        overrides.patientActivityComponent4
                      }
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        sty.patientActivityComponent4
                      )}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame93"}
                        data-plasmic-override={overrides.frame93}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.frame93)}
                      >
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame94"}
                          data-plasmic-override={overrides.frame94}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.frame94)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"headLine6"}
                            data-plasmic-override={overrides.headLine6}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.headLine6
                            )}
                          >
                            <div
                              data-plasmic-name={"h1Headline6"}
                              data-plasmic-override={overrides.h1Headline6}
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.h1Headline6
                              )}
                            >
                              {"${ActivityName}"}
                            </div>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"progressBarNot2"}
                            data-plasmic-override={overrides.progressBarNot2}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.progressBarNot2
                            )}
                          >
                            <div
                              data-plasmic-name={"frame2"}
                              data-plasmic-override={overrides.frame2}
                              className={classNames(defaultcss.all, sty.frame2)}
                            >
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.text__gyOnp
                                )}
                              >
                                {"0%"}
                              </div>
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame229"}
                        data-plasmic-override={overrides.frame229}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.frame229)}
                      >
                        <HomeWorkButton
                          _25={"_25" as const}
                          _50={"_50" as const}
                          className={classNames(
                            "__wab_instance",
                            sty.homeWorkButton___2THcS
                          )}
                        />

                        <HomeWorkButton
                          _25={"_25" as const}
                          _50={"_50" as const}
                          className={classNames(
                            "__wab_instance",
                            sty.homeWorkButton__hfqJe
                          )}
                        />
                      </p.Stack>

                      <div
                        data-plasmic-name={"frame247"}
                        data-plasmic-override={overrides.frame247}
                        className={classNames(defaultcss.all, sty.frame247)}
                      >
                        <div
                          data-plasmic-name={"body10Pt13"}
                          data-plasmic-override={overrides.body10Pt13}
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.body10Pt13
                          )}
                        >
                          {"see all >"}
                        </div>
                      </div>
                    </p.Stack>
                  </div>

                  <div
                    data-plasmic-name={"patientActivityComponent5"}
                    data-plasmic-override={overrides.patientActivityComponent5}
                    className={classNames(
                      defaultcss.all,
                      sty.patientActivityComponent5
                    )}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"patientActivityComponent6"}
                      data-plasmic-override={
                        overrides.patientActivityComponent6
                      }
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        sty.patientActivityComponent6
                      )}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame95"}
                        data-plasmic-override={overrides.frame95}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.frame95)}
                      >
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame96"}
                          data-plasmic-override={overrides.frame96}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.frame96)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"headLine7"}
                            data-plasmic-override={overrides.headLine7}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.headLine7
                            )}
                          >
                            <div
                              data-plasmic-name={"h1Headline7"}
                              data-plasmic-override={overrides.h1Headline7}
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.h1Headline7
                              )}
                            >
                              {"One Activity"}
                            </div>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"body12"}
                            data-plasmic-override={overrides.body12}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.body12)}
                          >
                            {false ? (
                              <div
                                data-plasmic-name={"body10Pt14"}
                                data-plasmic-override={overrides.body10Pt14}
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.body10Pt14
                                )}
                              >
                                {"Daily"}
                              </div>
                            ) : null}
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"progressBarNot3"}
                            data-plasmic-override={overrides.progressBarNot3}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.progressBarNot3
                            )}
                          >
                            <div
                              data-plasmic-name={"frame3"}
                              data-plasmic-override={overrides.frame3}
                              className={classNames(defaultcss.all, sty.frame3)}
                            >
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.text__gUJrF
                                )}
                              >
                                {"0%"}
                              </div>
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame230"}
                        data-plasmic-override={overrides.frame230}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.frame230)}
                      >
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"homeWork9"}
                          data-plasmic-override={overrides.homeWork9}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.homeWork9)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"body13"}
                            data-plasmic-override={overrides.body13}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.body13)}
                          >
                            <div
                              data-plasmic-name={"body10Pt15"}
                              data-plasmic-override={overrides.body10Pt15}
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.body10Pt15
                              )}
                            >
                              {"MO/DAY"}
                            </div>
                          </p.Stack>

                          <div
                            data-plasmic-name={"percentBall9"}
                            data-plasmic-override={overrides.percentBall9}
                            className={classNames(
                              defaultcss.all,
                              sty.percentBall9
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__kGmt
                              )}
                            >
                              {"0%"}
                            </div>

                            <Ellipse2Icon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__fNl1Q
                              )}
                              role={"img"}
                            />
                          </div>

                          <div
                            data-plasmic-name={"group98"}
                            data-plasmic-override={overrides.group98}
                            className={classNames(defaultcss.all, sty.group98)}
                          >
                            <div
                              data-plasmic-name={"arrowRightCircle16"}
                              data-plasmic-override={
                                overrides.arrowRightCircle16
                              }
                              className={classNames(
                                defaultcss.all,
                                sty.arrowRightCircle16
                              )}
                            >
                              <ArrowRightCircle3Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__vNiA
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"arrowRightCircle17"}
                              data-plasmic-override={
                                overrides.arrowRightCircle17
                              }
                              className={classNames(
                                defaultcss.all,
                                sty.arrowRightCircle17
                              )}
                            >
                              <ArrowRightCircle3Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__pcvE
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"homeWork10"}
                          data-plasmic-override={overrides.homeWork10}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.homeWork10)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"body14"}
                            data-plasmic-override={overrides.body14}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.body14)}
                          >
                            <div
                              data-plasmic-name={"body10Pt16"}
                              data-plasmic-override={overrides.body10Pt16}
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.body10Pt16
                              )}
                            >
                              {"MO/DAY"}
                            </div>
                          </p.Stack>

                          <div
                            data-plasmic-name={"percentBall10"}
                            data-plasmic-override={overrides.percentBall10}
                            className={classNames(
                              defaultcss.all,
                              sty.percentBall10
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__frKw1
                              )}
                            >
                              {"0%"}
                            </div>

                            <Ellipse2Icon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__veAgw
                              )}
                              role={"img"}
                            />
                          </div>

                          <div
                            data-plasmic-name={"group99"}
                            data-plasmic-override={overrides.group99}
                            className={classNames(defaultcss.all, sty.group99)}
                          >
                            <div
                              data-plasmic-name={"arrowRightCircle18"}
                              data-plasmic-override={
                                overrides.arrowRightCircle18
                              }
                              className={classNames(
                                defaultcss.all,
                                sty.arrowRightCircle18
                              )}
                            >
                              <ArrowRightCircle3Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__eeqG5
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"arrowRightCircle19"}
                              data-plasmic-override={
                                overrides.arrowRightCircle19
                              }
                              className={classNames(
                                defaultcss.all,
                                sty.arrowRightCircle19
                              )}
                            >
                              <ArrowRightCircle3Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__yhhJ
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"homeWork11"}
                          data-plasmic-override={overrides.homeWork11}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.homeWork11)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"body15"}
                            data-plasmic-override={overrides.body15}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.body15)}
                          >
                            <div
                              data-plasmic-name={"body10Pt17"}
                              data-plasmic-override={overrides.body10Pt17}
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.body10Pt17
                              )}
                            >
                              {"MO/DAY"}
                            </div>
                          </p.Stack>

                          <div
                            data-plasmic-name={"percentBall11"}
                            data-plasmic-override={overrides.percentBall11}
                            className={classNames(
                              defaultcss.all,
                              sty.percentBall11
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__deBe0
                              )}
                            >
                              {"0%"}
                            </div>

                            <Ellipse2Icon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__nn8YP
                              )}
                              role={"img"}
                            />
                          </div>

                          <div
                            data-plasmic-name={"group100"}
                            data-plasmic-override={overrides.group100}
                            className={classNames(defaultcss.all, sty.group100)}
                          >
                            <div
                              data-plasmic-name={"arrowRightCircle20"}
                              data-plasmic-override={
                                overrides.arrowRightCircle20
                              }
                              className={classNames(
                                defaultcss.all,
                                sty.arrowRightCircle20
                              )}
                            >
                              <ArrowRightCircle3Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__xzyy4
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"arrowRightCircle21"}
                              data-plasmic-override={
                                overrides.arrowRightCircle21
                              }
                              className={classNames(
                                defaultcss.all,
                                sty.arrowRightCircle21
                              )}
                            >
                              <ArrowRightCircle3Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__u8Rp
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"homeWork12"}
                          data-plasmic-override={overrides.homeWork12}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.homeWork12)}
                        >
                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"body16"}
                            data-plasmic-override={overrides.body16}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.body16)}
                          >
                            <div
                              data-plasmic-name={"body10Pt18"}
                              data-plasmic-override={overrides.body10Pt18}
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.body10Pt18
                              )}
                            >
                              {"MO/DAY"}
                            </div>
                          </p.Stack>

                          <div
                            data-plasmic-name={"percentBall12"}
                            data-plasmic-override={overrides.percentBall12}
                            className={classNames(
                              defaultcss.all,
                              sty.percentBall12
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.text__moe0R
                              )}
                            >
                              {"0%"}
                            </div>

                            <Ellipse2Icon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__efh8R
                              )}
                              role={"img"}
                            />
                          </div>

                          <div
                            data-plasmic-name={"group101"}
                            data-plasmic-override={overrides.group101}
                            className={classNames(defaultcss.all, sty.group101)}
                          >
                            <div
                              data-plasmic-name={"arrowRightCircle22"}
                              data-plasmic-override={
                                overrides.arrowRightCircle22
                              }
                              className={classNames(
                                defaultcss.all,
                                sty.arrowRightCircle22
                              )}
                            >
                              <ArrowRightCircle3Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__gNts1
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"arrowRightCircle23"}
                              data-plasmic-override={
                                overrides.arrowRightCircle23
                              }
                              className={classNames(
                                defaultcss.all,
                                sty.arrowRightCircle23
                              )}
                            >
                              <ArrowRightCircle3Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__nzgpt
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <div
                        data-plasmic-name={"frame248"}
                        data-plasmic-override={overrides.frame248}
                        className={classNames(defaultcss.all, sty.frame248)}
                      >
                        <div
                          data-plasmic-name={"body10Pt19"}
                          data-plasmic-override={overrides.body10Pt19}
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.body10Pt19
                          )}
                        >
                          {"see all >"}
                        </div>
                      </div>
                    </p.Stack>
                  </div>
                </p.Stack>
              </p.Stack>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "patientHomeScreen",
    "appBar",
    "settings",
    "headLine",
    "h1Headline",
    "notification",
    "searchBar",
    "frame206",
    "seachButton",
    "rectangle8",
    "group89",
    "tabs",
    "tabNames",
    "headLine2",
    "h1Headline2",
    "headLine3",
    "h1Headline3",
    "tab",
    "activeTabLine",
    "frame217",
    "rectangle389",
    "tabContent",
    "patientSessions",
    "sessionWidget",
    "arrowLeftCircle",
    "frame89",
    "frame90",
    "headLine4",
    "h1Headline4",
    "body",
    "body10Pt",
    "arrowRightCircle",
    "singleScrollable",
    "patientActivityComponent",
    "patientActivityComponent2",
    "frame91",
    "frame92",
    "headLine5",
    "h1Headline5",
    "progressBarNot",
    "frame1",
    "frame228",
    "frame246",
    "body10Pt7",
    "patientActivityComponent3",
    "patientActivityComponent4",
    "frame93",
    "frame94",
    "headLine6",
    "h1Headline6",
    "progressBarNot2",
    "frame2",
    "frame229",
    "frame247",
    "body10Pt13",
    "patientActivityComponent5",
    "patientActivityComponent6",
    "frame95",
    "frame96",
    "headLine7",
    "h1Headline7",
    "body12",
    "body10Pt14",
    "progressBarNot3",
    "frame3",
    "frame230",
    "homeWork9",
    "body13",
    "body10Pt15",
    "percentBall9",
    "group98",
    "arrowRightCircle16",
    "arrowRightCircle17",
    "homeWork10",
    "body14",
    "body10Pt16",
    "percentBall10",
    "group99",
    "arrowRightCircle18",
    "arrowRightCircle19",
    "homeWork11",
    "body15",
    "body10Pt17",
    "percentBall11",
    "group100",
    "arrowRightCircle20",
    "arrowRightCircle21",
    "homeWork12",
    "body16",
    "body10Pt18",
    "percentBall12",
    "group101",
    "arrowRightCircle22",
    "arrowRightCircle23",
    "frame248",
    "body10Pt19"
  ],
  patientHomeScreen: [
    "patientHomeScreen",
    "appBar",
    "settings",
    "headLine",
    "h1Headline",
    "notification",
    "searchBar",
    "frame206",
    "seachButton",
    "rectangle8",
    "group89",
    "tabs",
    "tabNames",
    "headLine2",
    "h1Headline2",
    "headLine3",
    "h1Headline3",
    "tab",
    "activeTabLine",
    "frame217",
    "rectangle389",
    "tabContent",
    "patientSessions",
    "sessionWidget",
    "arrowLeftCircle",
    "frame89",
    "frame90",
    "headLine4",
    "h1Headline4",
    "body",
    "body10Pt",
    "arrowRightCircle",
    "singleScrollable",
    "patientActivityComponent",
    "patientActivityComponent2",
    "frame91",
    "frame92",
    "headLine5",
    "h1Headline5",
    "progressBarNot",
    "frame1",
    "frame228",
    "frame246",
    "body10Pt7",
    "patientActivityComponent3",
    "patientActivityComponent4",
    "frame93",
    "frame94",
    "headLine6",
    "h1Headline6",
    "progressBarNot2",
    "frame2",
    "frame229",
    "frame247",
    "body10Pt13",
    "patientActivityComponent5",
    "patientActivityComponent6",
    "frame95",
    "frame96",
    "headLine7",
    "h1Headline7",
    "body12",
    "body10Pt14",
    "progressBarNot3",
    "frame3",
    "frame230",
    "homeWork9",
    "body13",
    "body10Pt15",
    "percentBall9",
    "group98",
    "arrowRightCircle16",
    "arrowRightCircle17",
    "homeWork10",
    "body14",
    "body10Pt16",
    "percentBall10",
    "group99",
    "arrowRightCircle18",
    "arrowRightCircle19",
    "homeWork11",
    "body15",
    "body10Pt17",
    "percentBall11",
    "group100",
    "arrowRightCircle20",
    "arrowRightCircle21",
    "homeWork12",
    "body16",
    "body10Pt18",
    "percentBall12",
    "group101",
    "arrowRightCircle22",
    "arrowRightCircle23",
    "frame248",
    "body10Pt19"
  ],
  appBar: ["appBar", "settings", "headLine", "h1Headline", "notification"],
  settings: ["settings"],
  headLine: ["headLine", "h1Headline"],
  h1Headline: ["h1Headline"],
  notification: ["notification"],
  searchBar: ["searchBar", "frame206", "seachButton", "rectangle8"],
  frame206: ["frame206"],
  seachButton: ["seachButton", "rectangle8"],
  rectangle8: ["rectangle8"],
  group89: [
    "group89",
    "tabs",
    "tabNames",
    "headLine2",
    "h1Headline2",
    "headLine3",
    "h1Headline3",
    "tab",
    "activeTabLine",
    "frame217",
    "rectangle389",
    "tabContent",
    "patientSessions",
    "sessionWidget",
    "arrowLeftCircle",
    "frame89",
    "frame90",
    "headLine4",
    "h1Headline4",
    "body",
    "body10Pt",
    "arrowRightCircle",
    "singleScrollable",
    "patientActivityComponent",
    "patientActivityComponent2",
    "frame91",
    "frame92",
    "headLine5",
    "h1Headline5",
    "progressBarNot",
    "frame1",
    "frame228",
    "frame246",
    "body10Pt7",
    "patientActivityComponent3",
    "patientActivityComponent4",
    "frame93",
    "frame94",
    "headLine6",
    "h1Headline6",
    "progressBarNot2",
    "frame2",
    "frame229",
    "frame247",
    "body10Pt13",
    "patientActivityComponent5",
    "patientActivityComponent6",
    "frame95",
    "frame96",
    "headLine7",
    "h1Headline7",
    "body12",
    "body10Pt14",
    "progressBarNot3",
    "frame3",
    "frame230",
    "homeWork9",
    "body13",
    "body10Pt15",
    "percentBall9",
    "group98",
    "arrowRightCircle16",
    "arrowRightCircle17",
    "homeWork10",
    "body14",
    "body10Pt16",
    "percentBall10",
    "group99",
    "arrowRightCircle18",
    "arrowRightCircle19",
    "homeWork11",
    "body15",
    "body10Pt17",
    "percentBall11",
    "group100",
    "arrowRightCircle20",
    "arrowRightCircle21",
    "homeWork12",
    "body16",
    "body10Pt18",
    "percentBall12",
    "group101",
    "arrowRightCircle22",
    "arrowRightCircle23",
    "frame248",
    "body10Pt19"
  ],
  tabs: [
    "tabs",
    "tabNames",
    "headLine2",
    "h1Headline2",
    "headLine3",
    "h1Headline3",
    "tab",
    "activeTabLine",
    "frame217",
    "rectangle389",
    "tabContent"
  ],
  tabNames: [
    "tabNames",
    "headLine2",
    "h1Headline2",
    "headLine3",
    "h1Headline3"
  ],
  headLine2: ["headLine2", "h1Headline2"],
  h1Headline2: ["h1Headline2"],
  headLine3: ["headLine3", "h1Headline3"],
  h1Headline3: ["h1Headline3"],
  tab: ["tab", "activeTabLine", "frame217", "rectangle389", "tabContent"],
  activeTabLine: ["activeTabLine", "frame217", "rectangle389"],
  frame217: ["frame217", "rectangle389"],
  rectangle389: ["rectangle389"],
  tabContent: ["tabContent"],
  patientSessions: [
    "patientSessions",
    "sessionWidget",
    "arrowLeftCircle",
    "frame89",
    "frame90",
    "headLine4",
    "h1Headline4",
    "body",
    "body10Pt",
    "arrowRightCircle",
    "singleScrollable",
    "patientActivityComponent",
    "patientActivityComponent2",
    "frame91",
    "frame92",
    "headLine5",
    "h1Headline5",
    "progressBarNot",
    "frame1",
    "frame228",
    "frame246",
    "body10Pt7",
    "patientActivityComponent3",
    "patientActivityComponent4",
    "frame93",
    "frame94",
    "headLine6",
    "h1Headline6",
    "progressBarNot2",
    "frame2",
    "frame229",
    "frame247",
    "body10Pt13",
    "patientActivityComponent5",
    "patientActivityComponent6",
    "frame95",
    "frame96",
    "headLine7",
    "h1Headline7",
    "body12",
    "body10Pt14",
    "progressBarNot3",
    "frame3",
    "frame230",
    "homeWork9",
    "body13",
    "body10Pt15",
    "percentBall9",
    "group98",
    "arrowRightCircle16",
    "arrowRightCircle17",
    "homeWork10",
    "body14",
    "body10Pt16",
    "percentBall10",
    "group99",
    "arrowRightCircle18",
    "arrowRightCircle19",
    "homeWork11",
    "body15",
    "body10Pt17",
    "percentBall11",
    "group100",
    "arrowRightCircle20",
    "arrowRightCircle21",
    "homeWork12",
    "body16",
    "body10Pt18",
    "percentBall12",
    "group101",
    "arrowRightCircle22",
    "arrowRightCircle23",
    "frame248",
    "body10Pt19"
  ],
  sessionWidget: [
    "sessionWidget",
    "arrowLeftCircle",
    "frame89",
    "frame90",
    "headLine4",
    "h1Headline4",
    "body",
    "body10Pt",
    "arrowRightCircle"
  ],
  arrowLeftCircle: ["arrowLeftCircle"],
  frame89: [
    "frame89",
    "frame90",
    "headLine4",
    "h1Headline4",
    "body",
    "body10Pt"
  ],
  frame90: ["frame90", "headLine4", "h1Headline4", "body", "body10Pt"],
  headLine4: ["headLine4", "h1Headline4"],
  h1Headline4: ["h1Headline4"],
  body: ["body", "body10Pt"],
  body10Pt: ["body10Pt"],
  arrowRightCircle: ["arrowRightCircle"],
  singleScrollable: [
    "singleScrollable",
    "patientActivityComponent",
    "patientActivityComponent2",
    "frame91",
    "frame92",
    "headLine5",
    "h1Headline5",
    "progressBarNot",
    "frame1",
    "frame228",
    "frame246",
    "body10Pt7",
    "patientActivityComponent3",
    "patientActivityComponent4",
    "frame93",
    "frame94",
    "headLine6",
    "h1Headline6",
    "progressBarNot2",
    "frame2",
    "frame229",
    "frame247",
    "body10Pt13",
    "patientActivityComponent5",
    "patientActivityComponent6",
    "frame95",
    "frame96",
    "headLine7",
    "h1Headline7",
    "body12",
    "body10Pt14",
    "progressBarNot3",
    "frame3",
    "frame230",
    "homeWork9",
    "body13",
    "body10Pt15",
    "percentBall9",
    "group98",
    "arrowRightCircle16",
    "arrowRightCircle17",
    "homeWork10",
    "body14",
    "body10Pt16",
    "percentBall10",
    "group99",
    "arrowRightCircle18",
    "arrowRightCircle19",
    "homeWork11",
    "body15",
    "body10Pt17",
    "percentBall11",
    "group100",
    "arrowRightCircle20",
    "arrowRightCircle21",
    "homeWork12",
    "body16",
    "body10Pt18",
    "percentBall12",
    "group101",
    "arrowRightCircle22",
    "arrowRightCircle23",
    "frame248",
    "body10Pt19"
  ],
  patientActivityComponent: [
    "patientActivityComponent",
    "patientActivityComponent2",
    "frame91",
    "frame92",
    "headLine5",
    "h1Headline5",
    "progressBarNot",
    "frame1",
    "frame228",
    "frame246",
    "body10Pt7"
  ],
  patientActivityComponent2: [
    "patientActivityComponent2",
    "frame91",
    "frame92",
    "headLine5",
    "h1Headline5",
    "progressBarNot",
    "frame1",
    "frame228",
    "frame246",
    "body10Pt7"
  ],
  frame91: [
    "frame91",
    "frame92",
    "headLine5",
    "h1Headline5",
    "progressBarNot",
    "frame1"
  ],
  frame92: ["frame92", "headLine5", "h1Headline5", "progressBarNot", "frame1"],
  headLine5: ["headLine5", "h1Headline5"],
  h1Headline5: ["h1Headline5"],
  progressBarNot: ["progressBarNot", "frame1"],
  frame1: ["frame1"],
  frame228: ["frame228"],
  frame246: ["frame246", "body10Pt7"],
  body10Pt7: ["body10Pt7"],
  patientActivityComponent3: [
    "patientActivityComponent3",
    "patientActivityComponent4",
    "frame93",
    "frame94",
    "headLine6",
    "h1Headline6",
    "progressBarNot2",
    "frame2",
    "frame229",
    "frame247",
    "body10Pt13"
  ],
  patientActivityComponent4: [
    "patientActivityComponent4",
    "frame93",
    "frame94",
    "headLine6",
    "h1Headline6",
    "progressBarNot2",
    "frame2",
    "frame229",
    "frame247",
    "body10Pt13"
  ],
  frame93: [
    "frame93",
    "frame94",
    "headLine6",
    "h1Headline6",
    "progressBarNot2",
    "frame2"
  ],
  frame94: ["frame94", "headLine6", "h1Headline6", "progressBarNot2", "frame2"],
  headLine6: ["headLine6", "h1Headline6"],
  h1Headline6: ["h1Headline6"],
  progressBarNot2: ["progressBarNot2", "frame2"],
  frame2: ["frame2"],
  frame229: ["frame229"],
  frame247: ["frame247", "body10Pt13"],
  body10Pt13: ["body10Pt13"],
  patientActivityComponent5: [
    "patientActivityComponent5",
    "patientActivityComponent6",
    "frame95",
    "frame96",
    "headLine7",
    "h1Headline7",
    "body12",
    "body10Pt14",
    "progressBarNot3",
    "frame3",
    "frame230",
    "homeWork9",
    "body13",
    "body10Pt15",
    "percentBall9",
    "group98",
    "arrowRightCircle16",
    "arrowRightCircle17",
    "homeWork10",
    "body14",
    "body10Pt16",
    "percentBall10",
    "group99",
    "arrowRightCircle18",
    "arrowRightCircle19",
    "homeWork11",
    "body15",
    "body10Pt17",
    "percentBall11",
    "group100",
    "arrowRightCircle20",
    "arrowRightCircle21",
    "homeWork12",
    "body16",
    "body10Pt18",
    "percentBall12",
    "group101",
    "arrowRightCircle22",
    "arrowRightCircle23",
    "frame248",
    "body10Pt19"
  ],
  patientActivityComponent6: [
    "patientActivityComponent6",
    "frame95",
    "frame96",
    "headLine7",
    "h1Headline7",
    "body12",
    "body10Pt14",
    "progressBarNot3",
    "frame3",
    "frame230",
    "homeWork9",
    "body13",
    "body10Pt15",
    "percentBall9",
    "group98",
    "arrowRightCircle16",
    "arrowRightCircle17",
    "homeWork10",
    "body14",
    "body10Pt16",
    "percentBall10",
    "group99",
    "arrowRightCircle18",
    "arrowRightCircle19",
    "homeWork11",
    "body15",
    "body10Pt17",
    "percentBall11",
    "group100",
    "arrowRightCircle20",
    "arrowRightCircle21",
    "homeWork12",
    "body16",
    "body10Pt18",
    "percentBall12",
    "group101",
    "arrowRightCircle22",
    "arrowRightCircle23",
    "frame248",
    "body10Pt19"
  ],
  frame95: [
    "frame95",
    "frame96",
    "headLine7",
    "h1Headline7",
    "body12",
    "body10Pt14",
    "progressBarNot3",
    "frame3"
  ],
  frame96: [
    "frame96",
    "headLine7",
    "h1Headline7",
    "body12",
    "body10Pt14",
    "progressBarNot3",
    "frame3"
  ],
  headLine7: ["headLine7", "h1Headline7"],
  h1Headline7: ["h1Headline7"],
  body12: ["body12", "body10Pt14"],
  body10Pt14: ["body10Pt14"],
  progressBarNot3: ["progressBarNot3", "frame3"],
  frame3: ["frame3"],
  frame230: [
    "frame230",
    "homeWork9",
    "body13",
    "body10Pt15",
    "percentBall9",
    "group98",
    "arrowRightCircle16",
    "arrowRightCircle17",
    "homeWork10",
    "body14",
    "body10Pt16",
    "percentBall10",
    "group99",
    "arrowRightCircle18",
    "arrowRightCircle19",
    "homeWork11",
    "body15",
    "body10Pt17",
    "percentBall11",
    "group100",
    "arrowRightCircle20",
    "arrowRightCircle21",
    "homeWork12",
    "body16",
    "body10Pt18",
    "percentBall12",
    "group101",
    "arrowRightCircle22",
    "arrowRightCircle23"
  ],
  homeWork9: [
    "homeWork9",
    "body13",
    "body10Pt15",
    "percentBall9",
    "group98",
    "arrowRightCircle16",
    "arrowRightCircle17"
  ],
  body13: ["body13", "body10Pt15"],
  body10Pt15: ["body10Pt15"],
  percentBall9: ["percentBall9"],
  group98: ["group98", "arrowRightCircle16", "arrowRightCircle17"],
  arrowRightCircle16: ["arrowRightCircle16"],
  arrowRightCircle17: ["arrowRightCircle17"],
  homeWork10: [
    "homeWork10",
    "body14",
    "body10Pt16",
    "percentBall10",
    "group99",
    "arrowRightCircle18",
    "arrowRightCircle19"
  ],
  body14: ["body14", "body10Pt16"],
  body10Pt16: ["body10Pt16"],
  percentBall10: ["percentBall10"],
  group99: ["group99", "arrowRightCircle18", "arrowRightCircle19"],
  arrowRightCircle18: ["arrowRightCircle18"],
  arrowRightCircle19: ["arrowRightCircle19"],
  homeWork11: [
    "homeWork11",
    "body15",
    "body10Pt17",
    "percentBall11",
    "group100",
    "arrowRightCircle20",
    "arrowRightCircle21"
  ],
  body15: ["body15", "body10Pt17"],
  body10Pt17: ["body10Pt17"],
  percentBall11: ["percentBall11"],
  group100: ["group100", "arrowRightCircle20", "arrowRightCircle21"],
  arrowRightCircle20: ["arrowRightCircle20"],
  arrowRightCircle21: ["arrowRightCircle21"],
  homeWork12: [
    "homeWork12",
    "body16",
    "body10Pt18",
    "percentBall12",
    "group101",
    "arrowRightCircle22",
    "arrowRightCircle23"
  ],
  body16: ["body16", "body10Pt18"],
  body10Pt18: ["body10Pt18"],
  percentBall12: ["percentBall12"],
  group101: ["group101", "arrowRightCircle22", "arrowRightCircle23"],
  arrowRightCircle22: ["arrowRightCircle22"],
  arrowRightCircle23: ["arrowRightCircle23"],
  frame248: ["frame248", "body10Pt19"],
  body10Pt19: ["body10Pt19"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  patientHomeScreen: "div";
  appBar: "div";
  settings: "div";
  headLine: "div";
  h1Headline: "div";
  notification: "div";
  searchBar: "div";
  frame206: "div";
  seachButton: "div";
  rectangle8: "div";
  group89: "div";
  tabs: "div";
  tabNames: "div";
  headLine2: "div";
  h1Headline2: "div";
  headLine3: "div";
  h1Headline3: "div";
  tab: "div";
  activeTabLine: "div";
  frame217: "div";
  rectangle389: "div";
  tabContent: "div";
  patientSessions: "div";
  sessionWidget: "div";
  arrowLeftCircle: "div";
  frame89: "div";
  frame90: "div";
  headLine4: "div";
  h1Headline4: "div";
  body: "div";
  body10Pt: "div";
  arrowRightCircle: "div";
  singleScrollable: "div";
  patientActivityComponent: "div";
  patientActivityComponent2: "div";
  frame91: "div";
  frame92: "div";
  headLine5: "div";
  h1Headline5: "div";
  progressBarNot: "div";
  frame1: "div";
  frame228: "div";
  frame246: "div";
  body10Pt7: "div";
  patientActivityComponent3: "div";
  patientActivityComponent4: "div";
  frame93: "div";
  frame94: "div";
  headLine6: "div";
  h1Headline6: "div";
  progressBarNot2: "div";
  frame2: "div";
  frame229: "div";
  frame247: "div";
  body10Pt13: "div";
  patientActivityComponent5: "div";
  patientActivityComponent6: "div";
  frame95: "div";
  frame96: "div";
  headLine7: "div";
  h1Headline7: "div";
  body12: "div";
  body10Pt14: "div";
  progressBarNot3: "div";
  frame3: "div";
  frame230: "div";
  homeWork9: "div";
  body13: "div";
  body10Pt15: "div";
  percentBall9: "div";
  group98: "div";
  arrowRightCircle16: "div";
  arrowRightCircle17: "div";
  homeWork10: "div";
  body14: "div";
  body10Pt16: "div";
  percentBall10: "div";
  group99: "div";
  arrowRightCircle18: "div";
  arrowRightCircle19: "div";
  homeWork11: "div";
  body15: "div";
  body10Pt17: "div";
  percentBall11: "div";
  group100: "div";
  arrowRightCircle20: "div";
  arrowRightCircle21: "div";
  homeWork12: "div";
  body16: "div";
  body10Pt18: "div";
  percentBall12: "div";
  group101: "div";
  arrowRightCircle22: "div";
  arrowRightCircle23: "div";
  frame248: "div";
  body10Pt19: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomePage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomePage__VariantsArgs;
    args?: PlasmicHomePage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomePage__Fetches;
  } & Omit<PlasmicHomePage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomePage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomePage__ArgProps,
      internalVariantPropNames: PlasmicHomePage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomePage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomePage";
  } else {
    func.displayName = `PlasmicHomePage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomePage = Object.assign(
  // Top-level PlasmicHomePage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    patientHomeScreen: makeNodeComponent("patientHomeScreen"),
    appBar: makeNodeComponent("appBar"),
    settings: makeNodeComponent("settings"),
    headLine: makeNodeComponent("headLine"),
    h1Headline: makeNodeComponent("h1Headline"),
    notification: makeNodeComponent("notification"),
    searchBar: makeNodeComponent("searchBar"),
    frame206: makeNodeComponent("frame206"),
    seachButton: makeNodeComponent("seachButton"),
    rectangle8: makeNodeComponent("rectangle8"),
    group89: makeNodeComponent("group89"),
    tabs: makeNodeComponent("tabs"),
    tabNames: makeNodeComponent("tabNames"),
    headLine2: makeNodeComponent("headLine2"),
    h1Headline2: makeNodeComponent("h1Headline2"),
    headLine3: makeNodeComponent("headLine3"),
    h1Headline3: makeNodeComponent("h1Headline3"),
    tab: makeNodeComponent("tab"),
    activeTabLine: makeNodeComponent("activeTabLine"),
    frame217: makeNodeComponent("frame217"),
    rectangle389: makeNodeComponent("rectangle389"),
    tabContent: makeNodeComponent("tabContent"),
    patientSessions: makeNodeComponent("patientSessions"),
    sessionWidget: makeNodeComponent("sessionWidget"),
    arrowLeftCircle: makeNodeComponent("arrowLeftCircle"),
    frame89: makeNodeComponent("frame89"),
    frame90: makeNodeComponent("frame90"),
    headLine4: makeNodeComponent("headLine4"),
    h1Headline4: makeNodeComponent("h1Headline4"),
    body: makeNodeComponent("body"),
    body10Pt: makeNodeComponent("body10Pt"),
    arrowRightCircle: makeNodeComponent("arrowRightCircle"),
    singleScrollable: makeNodeComponent("singleScrollable"),
    patientActivityComponent: makeNodeComponent("patientActivityComponent"),
    patientActivityComponent2: makeNodeComponent("patientActivityComponent2"),
    frame91: makeNodeComponent("frame91"),
    frame92: makeNodeComponent("frame92"),
    headLine5: makeNodeComponent("headLine5"),
    h1Headline5: makeNodeComponent("h1Headline5"),
    progressBarNot: makeNodeComponent("progressBarNot"),
    frame1: makeNodeComponent("frame1"),
    frame228: makeNodeComponent("frame228"),
    frame246: makeNodeComponent("frame246"),
    body10Pt7: makeNodeComponent("body10Pt7"),
    patientActivityComponent3: makeNodeComponent("patientActivityComponent3"),
    patientActivityComponent4: makeNodeComponent("patientActivityComponent4"),
    frame93: makeNodeComponent("frame93"),
    frame94: makeNodeComponent("frame94"),
    headLine6: makeNodeComponent("headLine6"),
    h1Headline6: makeNodeComponent("h1Headline6"),
    progressBarNot2: makeNodeComponent("progressBarNot2"),
    frame2: makeNodeComponent("frame2"),
    frame229: makeNodeComponent("frame229"),
    frame247: makeNodeComponent("frame247"),
    body10Pt13: makeNodeComponent("body10Pt13"),
    patientActivityComponent5: makeNodeComponent("patientActivityComponent5"),
    patientActivityComponent6: makeNodeComponent("patientActivityComponent6"),
    frame95: makeNodeComponent("frame95"),
    frame96: makeNodeComponent("frame96"),
    headLine7: makeNodeComponent("headLine7"),
    h1Headline7: makeNodeComponent("h1Headline7"),
    body12: makeNodeComponent("body12"),
    body10Pt14: makeNodeComponent("body10Pt14"),
    progressBarNot3: makeNodeComponent("progressBarNot3"),
    frame3: makeNodeComponent("frame3"),
    frame230: makeNodeComponent("frame230"),
    homeWork9: makeNodeComponent("homeWork9"),
    body13: makeNodeComponent("body13"),
    body10Pt15: makeNodeComponent("body10Pt15"),
    percentBall9: makeNodeComponent("percentBall9"),
    group98: makeNodeComponent("group98"),
    arrowRightCircle16: makeNodeComponent("arrowRightCircle16"),
    arrowRightCircle17: makeNodeComponent("arrowRightCircle17"),
    homeWork10: makeNodeComponent("homeWork10"),
    body14: makeNodeComponent("body14"),
    body10Pt16: makeNodeComponent("body10Pt16"),
    percentBall10: makeNodeComponent("percentBall10"),
    group99: makeNodeComponent("group99"),
    arrowRightCircle18: makeNodeComponent("arrowRightCircle18"),
    arrowRightCircle19: makeNodeComponent("arrowRightCircle19"),
    homeWork11: makeNodeComponent("homeWork11"),
    body15: makeNodeComponent("body15"),
    body10Pt17: makeNodeComponent("body10Pt17"),
    percentBall11: makeNodeComponent("percentBall11"),
    group100: makeNodeComponent("group100"),
    arrowRightCircle20: makeNodeComponent("arrowRightCircle20"),
    arrowRightCircle21: makeNodeComponent("arrowRightCircle21"),
    homeWork12: makeNodeComponent("homeWork12"),
    body16: makeNodeComponent("body16"),
    body10Pt18: makeNodeComponent("body10Pt18"),
    percentBall12: makeNodeComponent("percentBall12"),
    group101: makeNodeComponent("group101"),
    arrowRightCircle22: makeNodeComponent("arrowRightCircle22"),
    arrowRightCircle23: makeNodeComponent("arrowRightCircle23"),
    frame248: makeNodeComponent("frame248"),
    body10Pt19: makeNodeComponent("body10Pt19"),

    // Metadata about props expected for PlasmicHomePage
    internalVariantProps: PlasmicHomePage__VariantProps,
    internalArgProps: PlasmicHomePage__ArgProps
  }
);

export default PlasmicHomePage;
/* prettier-ignore-end */
